services:
  database:
    container_name: safe_co
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: safe_co
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data